//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", ConfigurationName="ServiceReference1.PUGSoap")]
    public interface PUGSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/AssayDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DownloadKey")]
        System.Threading.Tasks.Task<string> AssayDownloadAsync(string AssayKey, ServiceReference1.AssayFormatType AssayFormat, ServiceReference1.CompressType eCompress);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/Download", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.DownloadResponse> DownloadAsync(ServiceReference1.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetAssayColumnDescription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ColumnDescription")]
        System.Threading.Tasks.Task<ServiceReference1.ColumnDescriptionType> GetAssayColumnDescriptionAsync(int AID, ServiceReference1.HeadingType Heading, int TID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetAssayColumnDescriptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetAssayColumnDescriptionsResponse> GetAssayColumnDescriptionsAsync(ServiceReference1.GetAssayColumnDescriptionsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetAssayDescription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetAssayDescriptionResponse> GetAssayDescriptionAsync(ServiceReference1.GetAssayDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetDownloadUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="url")]
        System.Threading.Tasks.Task<string> GetDownloadUrlAsync(string DownloadKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetEntrezKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="EntrezKey")]
        System.Threading.Tasks.Task<ServiceReference1.EntrezKey> GetEntrezKeyAsync(string ListKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetEntrezUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="url")]
        System.Threading.Tasks.Task<string> GetEntrezUrlAsync(ServiceReference1.EntrezKey EntrezKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetIDList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="IDList")]
        System.Threading.Tasks.Task<int[]> GetIDListAsync(string ListKey, int Start, int Count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetListItemsCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="count")]
        System.Threading.Tasks.Task<int> GetListItemsCountAsync(string ListKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetOperationStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        System.Threading.Tasks.Task<ServiceReference1.StatusType> GetOperationStatusAsync(string AnyKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetStandardizedCID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CID")]
        System.Threading.Tasks.Task<int> GetStandardizedCIDAsync(string StrKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetStandardizedStructure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="structure")]
        System.Threading.Tasks.Task<string> GetStandardizedStructureAsync(string StrKey, ServiceReference1.FormatType format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetStandardizedStructureBase64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetStandardizedStructureBase64Response> GetStandardizedStructureBase64Async(ServiceReference1.GetStandardizedStructureBase64Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/GetStatusMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="message")]
        System.Threading.Tasks.Task<string> GetStatusMessageAsync(string AnyKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/IdentitySearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ListKey")]
        System.Threading.Tasks.Task<string> IdentitySearchAsync(string StrKey, ServiceReference1.IdentitySearchOptions idOptions, ServiceReference1.LimitsType limits);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/IDExchange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.IDExchangeResponse> IDExchangeAsync(ServiceReference1.IDExchangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/InputAssay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="AssayKey")]
        System.Threading.Tasks.Task<string> InputAssayAsync(int AID, ServiceReference1.AssayColumnsType Columns, string ListKeyTIDs, string ListKeySCIDs, ServiceReference1.AssayOutcomeFilterType OutcomeFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/InputEntrez", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ListKey")]
        System.Threading.Tasks.Task<string> InputEntrezAsync(ServiceReference1.EntrezKey EntrezKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/InputList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ListKey")]
        System.Threading.Tasks.Task<string> InputListAsync(int[] ids, ServiceReference1.PCIDType idType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/InputListString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.InputListStringResponse> InputListStringAsync(ServiceReference1.InputListStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/InputListText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ListKey")]
        System.Threading.Tasks.Task<string> InputListTextAsync(string ids, ServiceReference1.PCIDType idType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/InputStructure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StrKey")]
        System.Threading.Tasks.Task<string> InputStructureAsync(string structure, ServiceReference1.FormatType format);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/InputStructureBase64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.InputStructureBase64Response> InputStructureBase64Async(ServiceReference1.InputStructureBase64Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/MFSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ListKey")]
        System.Threading.Tasks.Task<string> MFSearchAsync(string MF, ServiceReference1.MFSearchOptions mfOptions, ServiceReference1.LimitsType limits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/ScoreMatrix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DownloadKey")]
        System.Threading.Tasks.Task<string> ScoreMatrixAsync(string ListKey, string SecondaryListKey, ServiceReference1.ScoreTypeType ScoreType, ServiceReference1.MatrixFormatType MatrixFormat, ServiceReference1.CompressType eCompress, int N3DConformers, bool No3DParent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/SimilaritySearch2D", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ListKey")]
        System.Threading.Tasks.Task<string> SimilaritySearch2DAsync(string StrKey, ServiceReference1.SimilaritySearchOptions simOptions, ServiceReference1.LimitsType limits);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/Standardize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.StandardizeResponse> StandardizeAsync(ServiceReference1.StandardizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/SubstructureSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ListKey")]
        System.Threading.Tasks.Task<string> SubstructureSearchAsync(string StrKey, ServiceReference1.StructureSearchOptions ssOptions, ServiceReference1.LimitsType limits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pubchem.ncbi.nlm.nih.gov/SuperstructureSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ListKey")]
        System.Threading.Tasks.Task<string> SuperstructureSearchAsync(string StrKey, ServiceReference1.StructureSearchOptions ssOptions, ServiceReference1.LimitsType limits);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum AssayFormatType
    {
        
        /// <remarks/>
        eAssayFormat_XML,
        
        /// <remarks/>
        eAssayFormat_ASN_Text,
        
        /// <remarks/>
        eAssayFormat_ASN_Binary,
        
        /// <remarks/>
        eAssayFormat_CSV,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum CompressType
    {
        
        /// <remarks/>
        eCompress_None,
        
        /// <remarks/>
        eCompress_GZip,
        
        /// <remarks/>
        eCompress_BZip2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum FormatType
    {
        
        /// <remarks/>
        eFormat_ASNB,
        
        /// <remarks/>
        eFormat_ASNT,
        
        /// <remarks/>
        eFormat_XML,
        
        /// <remarks/>
        eFormat_SDF,
        
        /// <remarks/>
        eFormat_SMILES,
        
        /// <remarks/>
        eFormat_InChI,
        
        /// <remarks/>
        eFormat_Image,
        
        /// <remarks/>
        eFormat_Thumbnail,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class DataBlobType
    {
        
        private byte[] dataField;
        
        private BlobFormatType blobFormatField;
        
        private bool blobFormatFieldSpecified;
        
        private CompressType eCompressField;
        
        private bool eCompressFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BlobFormatType BlobFormat
        {
            get
            {
                return this.blobFormatField;
            }
            set
            {
                this.blobFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlobFormatSpecified
        {
            get
            {
                return this.blobFormatFieldSpecified;
            }
            set
            {
                this.blobFormatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CompressType eCompress
        {
            get
            {
                return this.eCompressField;
            }
            set
            {
                this.eCompressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eCompressSpecified
        {
            get
            {
                return this.eCompressFieldSpecified;
            }
            set
            {
                this.eCompressFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum BlobFormatType
    {
        
        /// <remarks/>
        eBlobFormat_Unspecified,
        
        /// <remarks/>
        eBlobFormat_ASNB,
        
        /// <remarks/>
        eBlobFormat_ASNT,
        
        /// <remarks/>
        eBlobFormat_XML,
        
        /// <remarks/>
        eBlobFormat_SDF,
        
        /// <remarks/>
        eBlobFormat_CSV,
        
        /// <remarks/>
        eBlobFormat_Text,
        
        /// <remarks/>
        eBlobFormat_HTML,
        
        /// <remarks/>
        eBlobFormat_PNG,
        
        /// <remarks/>
        eBlobFormat_Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class StructureSearchOptions
    {
        
        private bool matchIsotopesField;
        
        private bool matchIsotopesFieldSpecified;
        
        private bool matchChargesField;
        
        private bool matchChargesFieldSpecified;
        
        private bool matchTautomersField;
        
        private bool matchTautomersFieldSpecified;
        
        private bool ringsNotEmbeddedField;
        
        private bool ringsNotEmbeddedFieldSpecified;
        
        private bool singeDoubleBondsMatchField;
        
        private bool singeDoubleBondsMatchFieldSpecified;
        
        private bool chainsMatchRingsField;
        
        private bool chainsMatchRingsFieldSpecified;
        
        private bool stripHydrogenField;
        
        private bool stripHydrogenFieldSpecified;
        
        private StereoType eStereoField;
        
        private bool eStereoFieldSpecified;
        
        private string toWebEnvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool MatchIsotopes
        {
            get
            {
                return this.matchIsotopesField;
            }
            set
            {
                this.matchIsotopesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MatchIsotopesSpecified
        {
            get
            {
                return this.matchIsotopesFieldSpecified;
            }
            set
            {
                this.matchIsotopesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool MatchCharges
        {
            get
            {
                return this.matchChargesField;
            }
            set
            {
                this.matchChargesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MatchChargesSpecified
        {
            get
            {
                return this.matchChargesFieldSpecified;
            }
            set
            {
                this.matchChargesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool MatchTautomers
        {
            get
            {
                return this.matchTautomersField;
            }
            set
            {
                this.matchTautomersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MatchTautomersSpecified
        {
            get
            {
                return this.matchTautomersFieldSpecified;
            }
            set
            {
                this.matchTautomersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool RingsNotEmbedded
        {
            get
            {
                return this.ringsNotEmbeddedField;
            }
            set
            {
                this.ringsNotEmbeddedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RingsNotEmbeddedSpecified
        {
            get
            {
                return this.ringsNotEmbeddedFieldSpecified;
            }
            set
            {
                this.ringsNotEmbeddedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool SingeDoubleBondsMatch
        {
            get
            {
                return this.singeDoubleBondsMatchField;
            }
            set
            {
                this.singeDoubleBondsMatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SingeDoubleBondsMatchSpecified
        {
            get
            {
                return this.singeDoubleBondsMatchFieldSpecified;
            }
            set
            {
                this.singeDoubleBondsMatchFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ChainsMatchRings
        {
            get
            {
                return this.chainsMatchRingsField;
            }
            set
            {
                this.chainsMatchRingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChainsMatchRingsSpecified
        {
            get
            {
                return this.chainsMatchRingsFieldSpecified;
            }
            set
            {
                this.chainsMatchRingsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool StripHydrogen
        {
            get
            {
                return this.stripHydrogenField;
            }
            set
            {
                this.stripHydrogenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StripHydrogenSpecified
        {
            get
            {
                return this.stripHydrogenFieldSpecified;
            }
            set
            {
                this.stripHydrogenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public StereoType eStereo
        {
            get
            {
                return this.eStereoField;
            }
            set
            {
                this.eStereoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eStereoSpecified
        {
            get
            {
                return this.eStereoFieldSpecified;
            }
            set
            {
                this.eStereoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ToWebEnv
        {
            get
            {
                return this.toWebEnvField;
            }
            set
            {
                this.toWebEnvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum StereoType
    {
        
        /// <remarks/>
        eStereo_Ignore,
        
        /// <remarks/>
        eStereo_Exact,
        
        /// <remarks/>
        eStereo_Relative,
        
        /// <remarks/>
        eStereo_NonConflicting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class SimilaritySearchOptions
    {
        
        private int thresholdField;
        
        private string toWebEnvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int threshold
        {
            get
            {
                return this.thresholdField;
            }
            set
            {
                this.thresholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ToWebEnv
        {
            get
            {
                return this.toWebEnvField;
            }
            set
            {
                this.toWebEnvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class MFSearchOptions
    {
        
        private bool allowOtherElementsField;
        
        private string toWebEnvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AllowOtherElements
        {
            get
            {
                return this.allowOtherElementsField;
            }
            set
            {
                this.allowOtherElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ToWebEnv
        {
            get
            {
                return this.toWebEnvField;
            }
            set
            {
                this.toWebEnvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class LimitsType
    {
        
        private int secondsField;
        
        private bool secondsFieldSpecified;
        
        private int maxRecordsField;
        
        private bool maxRecordsFieldSpecified;
        
        private string listKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int seconds
        {
            get
            {
                return this.secondsField;
            }
            set
            {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondsSpecified
        {
            get
            {
                return this.secondsFieldSpecified;
            }
            set
            {
                this.secondsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int maxRecords
        {
            get
            {
                return this.maxRecordsField;
            }
            set
            {
                this.maxRecordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxRecordsSpecified
        {
            get
            {
                return this.maxRecordsFieldSpecified;
            }
            set
            {
                this.maxRecordsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ListKey
        {
            get
            {
                return this.listKeyField;
            }
            set
            {
                this.listKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class IdentitySearchOptions
    {
        
        private IdentityType eIdentityField;
        
        private string toWebEnvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentityType eIdentity
        {
            get
            {
                return this.eIdentityField;
            }
            set
            {
                this.eIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ToWebEnv
        {
            get
            {
                return this.toWebEnvField;
            }
            set
            {
                this.toWebEnvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum IdentityType
    {
        
        /// <remarks/>
        eIdentity_SameConnectivity,
        
        /// <remarks/>
        eIdentity_AnyTautomer,
        
        /// <remarks/>
        eIdentity_SameStereo,
        
        /// <remarks/>
        eIdentity_SameIsotope,
        
        /// <remarks/>
        eIdentity_SameStereoIsotope,
        
        /// <remarks/>
        eIdentity_SameNonconflictStereo,
        
        /// <remarks/>
        eIdentity_SameIsotopeNonconflictStereo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class EntrezKey
    {
        
        private string dbField;
        
        private string keyField;
        
        private string webenvField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string db
        {
            get
            {
                return this.dbField;
            }
            set
            {
                this.dbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string webenv
        {
            get
            {
                return this.webenvField;
            }
            set
            {
                this.webenvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class AssayTargetType
    {
        
        private int giField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int gi
        {
            get
            {
                return this.giField;
            }
            set
            {
                this.giField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class AssayDescriptionType
    {
        
        private string nameField;
        
        private string[] descriptionField;
        
        private string[] protocolField;
        
        private string[] commentField;
        
        private int numberOfTIDsField;
        
        private bool hasScoreField;
        
        private string methodField;
        
        private AssayTargetType[] targetsField;
        
        private int versionField;
        
        private bool versionFieldSpecified;
        
        private int revisionField;
        
        private bool revisionFieldSpecified;
        
        private int lastDataChangeField;
        
        private bool lastDataChangeFieldSpecified;
        
        private int sIDCountAllField;
        
        private bool sIDCountAllFieldSpecified;
        
        private int sIDCountActiveField;
        
        private bool sIDCountActiveFieldSpecified;
        
        private int sIDCountInactiveField;
        
        private bool sIDCountInactiveFieldSpecified;
        
        private int sIDCountInconclusiveField;
        
        private bool sIDCountInconclusiveFieldSpecified;
        
        private int sIDCountUnspecifiedField;
        
        private bool sIDCountUnspecifiedFieldSpecified;
        
        private int sIDCountProbeField;
        
        private bool sIDCountProbeFieldSpecified;
        
        private int cIDCountAllField;
        
        private bool cIDCountAllFieldSpecified;
        
        private int cIDCountActiveField;
        
        private bool cIDCountActiveFieldSpecified;
        
        private int cIDCountInactiveField;
        
        private bool cIDCountInactiveFieldSpecified;
        
        private int cIDCountInconclusiveField;
        
        private bool cIDCountInconclusiveFieldSpecified;
        
        private int cIDCountUnspecifiedField;
        
        private bool cIDCountUnspecifiedFieldSpecified;
        
        private int cIDCountProbeField;
        
        private bool cIDCountProbeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] Protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int NumberOfTIDs
        {
            get
            {
                return this.numberOfTIDsField;
            }
            set
            {
                this.numberOfTIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool HasScore
        {
            get
            {
                return this.hasScoreField;
            }
            set
            {
                this.hasScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Target", IsNullable=false)]
        public AssayTargetType[] Targets
        {
            get
            {
                return this.targetsField;
            }
            set
            {
                this.targetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VersionSpecified
        {
            get
            {
                return this.versionFieldSpecified;
            }
            set
            {
                this.versionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RevisionSpecified
        {
            get
            {
                return this.revisionFieldSpecified;
            }
            set
            {
                this.revisionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int LastDataChange
        {
            get
            {
                return this.lastDataChangeField;
            }
            set
            {
                this.lastDataChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastDataChangeSpecified
        {
            get
            {
                return this.lastDataChangeFieldSpecified;
            }
            set
            {
                this.lastDataChangeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int SIDCountAll
        {
            get
            {
                return this.sIDCountAllField;
            }
            set
            {
                this.sIDCountAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SIDCountAllSpecified
        {
            get
            {
                return this.sIDCountAllFieldSpecified;
            }
            set
            {
                this.sIDCountAllFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int SIDCountActive
        {
            get
            {
                return this.sIDCountActiveField;
            }
            set
            {
                this.sIDCountActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SIDCountActiveSpecified
        {
            get
            {
                return this.sIDCountActiveFieldSpecified;
            }
            set
            {
                this.sIDCountActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int SIDCountInactive
        {
            get
            {
                return this.sIDCountInactiveField;
            }
            set
            {
                this.sIDCountInactiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SIDCountInactiveSpecified
        {
            get
            {
                return this.sIDCountInactiveFieldSpecified;
            }
            set
            {
                this.sIDCountInactiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int SIDCountInconclusive
        {
            get
            {
                return this.sIDCountInconclusiveField;
            }
            set
            {
                this.sIDCountInconclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SIDCountInconclusiveSpecified
        {
            get
            {
                return this.sIDCountInconclusiveFieldSpecified;
            }
            set
            {
                this.sIDCountInconclusiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int SIDCountUnspecified
        {
            get
            {
                return this.sIDCountUnspecifiedField;
            }
            set
            {
                this.sIDCountUnspecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SIDCountUnspecifiedSpecified
        {
            get
            {
                return this.sIDCountUnspecifiedFieldSpecified;
            }
            set
            {
                this.sIDCountUnspecifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int SIDCountProbe
        {
            get
            {
                return this.sIDCountProbeField;
            }
            set
            {
                this.sIDCountProbeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SIDCountProbeSpecified
        {
            get
            {
                return this.sIDCountProbeFieldSpecified;
            }
            set
            {
                this.sIDCountProbeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int CIDCountAll
        {
            get
            {
                return this.cIDCountAllField;
            }
            set
            {
                this.cIDCountAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CIDCountAllSpecified
        {
            get
            {
                return this.cIDCountAllFieldSpecified;
            }
            set
            {
                this.cIDCountAllFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int CIDCountActive
        {
            get
            {
                return this.cIDCountActiveField;
            }
            set
            {
                this.cIDCountActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CIDCountActiveSpecified
        {
            get
            {
                return this.cIDCountActiveFieldSpecified;
            }
            set
            {
                this.cIDCountActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int CIDCountInactive
        {
            get
            {
                return this.cIDCountInactiveField;
            }
            set
            {
                this.cIDCountInactiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CIDCountInactiveSpecified
        {
            get
            {
                return this.cIDCountInactiveFieldSpecified;
            }
            set
            {
                this.cIDCountInactiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int CIDCountInconclusive
        {
            get
            {
                return this.cIDCountInconclusiveField;
            }
            set
            {
                this.cIDCountInconclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CIDCountInconclusiveSpecified
        {
            get
            {
                return this.cIDCountInconclusiveFieldSpecified;
            }
            set
            {
                this.cIDCountInconclusiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int CIDCountUnspecified
        {
            get
            {
                return this.cIDCountUnspecifiedField;
            }
            set
            {
                this.cIDCountUnspecifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CIDCountUnspecifiedSpecified
        {
            get
            {
                return this.cIDCountUnspecifiedFieldSpecified;
            }
            set
            {
                this.cIDCountUnspecifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int CIDCountProbe
        {
            get
            {
                return this.cIDCountProbeField;
            }
            set
            {
                this.cIDCountProbeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CIDCountProbeSpecified
        {
            get
            {
                return this.cIDCountProbeFieldSpecified;
            }
            set
            {
                this.cIDCountProbeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class TestedConcentrationType
    {
        
        private double concentrationField;
        
        private string unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Concentration
        {
            get
            {
                return this.concentrationField;
            }
            set
            {
                this.concentrationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public partial class ColumnDescriptionType
    {
        
        private HeadingType headingField;
        
        private int tIDField;
        
        private bool tIDFieldSpecified;
        
        private string nameField;
        
        private string[] descriptionField;
        
        private string typeField;
        
        private string unitField;
        
        private TestedConcentrationType testedConcentrationField;
        
        private bool activeConcentrationField;
        
        private bool activeConcentrationFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HeadingType Heading
        {
            get
            {
                return this.headingField;
            }
            set
            {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TID
        {
            get
            {
                return this.tIDField;
            }
            set
            {
                this.tIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TIDSpecified
        {
            get
            {
                return this.tIDFieldSpecified;
            }
            set
            {
                this.tIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public TestedConcentrationType TestedConcentration
        {
            get
            {
                return this.testedConcentrationField;
            }
            set
            {
                this.testedConcentrationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool ActiveConcentration
        {
            get
            {
                return this.activeConcentrationField;
            }
            set
            {
                this.activeConcentrationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveConcentrationSpecified
        {
            get
            {
                return this.activeConcentrationFieldSpecified;
            }
            set
            {
                this.activeConcentrationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum HeadingType
    {
        
        /// <remarks/>
        TID,
        
        /// <remarks/>
        outcome,
        
        /// <remarks/>
        score,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Download", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class DownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string ListKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public ServiceReference1.FormatType eFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=2)]
        public ServiceReference1.CompressType eCompress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=3)]
        public bool Use3D;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=4)]
        public int N3DConformers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=5)]
        public bool SynchronousSingleRecord;
        
        public DownloadRequest()
        {
        }
        
        public DownloadRequest(string ListKey, ServiceReference1.FormatType eFormat, ServiceReference1.CompressType eCompress, bool Use3D, int N3DConformers, bool SynchronousSingleRecord)
        {
            this.ListKey = ListKey;
            this.eFormat = eFormat;
            this.eCompress = eCompress;
            this.Use3D = Use3D;
            this.N3DConformers = N3DConformers;
            this.SynchronousSingleRecord = SynchronousSingleRecord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadResponse", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class DownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string DownloadKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public ServiceReference1.DataBlobType DataBlob;
        
        public DownloadResponse()
        {
        }
        
        public DownloadResponse(string DownloadKey, ServiceReference1.DataBlobType DataBlob)
        {
            this.DownloadKey = DownloadKey;
            this.DataBlob = DataBlob;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssayColumnDescriptions", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class GetAssayColumnDescriptionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public int AID;
        
        public GetAssayColumnDescriptionsRequest()
        {
        }
        
        public GetAssayColumnDescriptionsRequest(int AID)
        {
            this.AID = AID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssayColumnDescriptionsResponse", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class GetAssayColumnDescriptionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ColumnDescription")]
        public ServiceReference1.ColumnDescriptionType[] ColumnDescription;
        
        public GetAssayColumnDescriptionsResponse()
        {
        }
        
        public GetAssayColumnDescriptionsResponse(ServiceReference1.ColumnDescriptionType[] ColumnDescription)
        {
            this.ColumnDescription = ColumnDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssayDescription", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class GetAssayDescriptionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public int AID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public bool GetVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=2)]
        public bool GetCounts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=3)]
        public bool GetFullDataBlob;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=4)]
        public ServiceReference1.FormatType eFormat;
        
        public GetAssayDescriptionRequest()
        {
        }
        
        public GetAssayDescriptionRequest(int AID, bool GetVersion, bool GetCounts, bool GetFullDataBlob, ServiceReference1.FormatType eFormat)
        {
            this.AID = AID;
            this.GetVersion = GetVersion;
            this.GetCounts = GetCounts;
            this.GetFullDataBlob = GetFullDataBlob;
            this.eFormat = eFormat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAssayDescriptionResponse", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class GetAssayDescriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public ServiceReference1.AssayDescriptionType AssayDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public ServiceReference1.DataBlobType DataBlob;
        
        public GetAssayDescriptionResponse()
        {
        }
        
        public GetAssayDescriptionResponse(ServiceReference1.AssayDescriptionType AssayDescription, ServiceReference1.DataBlobType DataBlob)
        {
            this.AssayDescription = AssayDescription;
            this.DataBlob = DataBlob;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum StatusType
    {
        
        /// <remarks/>
        eStatus_Unknown,
        
        /// <remarks/>
        eStatus_Success,
        
        /// <remarks/>
        eStatus_ServerError,
        
        /// <remarks/>
        eStatus_HitLimit,
        
        /// <remarks/>
        eStatus_TimeLimit,
        
        /// <remarks/>
        eStatus_InputError,
        
        /// <remarks/>
        eStatus_DataError,
        
        /// <remarks/>
        eStatus_Stopped,
        
        /// <remarks/>
        eStatus_Running,
        
        /// <remarks/>
        eStatus_Queued,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStandardizedStructureBase64", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class GetStandardizedStructureBase64Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string StrKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public ServiceReference1.FormatType format;
        
        public GetStandardizedStructureBase64Request()
        {
        }
        
        public GetStandardizedStructureBase64Request(string StrKey, ServiceReference1.FormatType format)
        {
            this.StrKey = StrKey;
            this.format = format;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStandardizedStructureBase64Response", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class GetStandardizedStructureBase64Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] structure;
        
        public GetStandardizedStructureBase64Response()
        {
        }
        
        public GetStandardizedStructureBase64Response(byte[] structure)
        {
            this.structure = structure;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum IDOperationType
    {
        
        /// <remarks/>
        eIDOperation_Same,
        
        /// <remarks/>
        eIDOperation_SameStereo,
        
        /// <remarks/>
        eIDOperation_SameIsotope,
        
        /// <remarks/>
        eIDOperation_SameConnectivity,
        
        /// <remarks/>
        eIDOperation_SameParent,
        
        /// <remarks/>
        eIDOperation_SameParentStereo,
        
        /// <remarks/>
        eIDOperation_SameParentIsotope,
        
        /// <remarks/>
        eIDOperation_SameParentConnectivity,
        
        /// <remarks/>
        eIDOperation_Similar2D,
        
        /// <remarks/>
        eIDOperation_Similar3D,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum PCIDType
    {
        
        /// <remarks/>
        eID_CID,
        
        /// <remarks/>
        eID_SID,
        
        /// <remarks/>
        eID_AID,
        
        /// <remarks/>
        eID_TID,
        
        /// <remarks/>
        eID_ConformerID,
        
        /// <remarks/>
        eID_SourceID,
        
        /// <remarks/>
        eID_InChI,
        
        /// <remarks/>
        eID_InChIKey,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum IDOutputFormatType
    {
        
        /// <remarks/>
        eIDOutputFormat_Entrez,
        
        /// <remarks/>
        eIDOutputFormat_FileList,
        
        /// <remarks/>
        eIDOutputFormat_FilePair,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IDExchange", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class IDExchangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string InputListKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public ServiceReference1.IDOperationType Operation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=2)]
        public ServiceReference1.PCIDType OutputType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=3)]
        public string OutputSourceName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=4)]
        public ServiceReference1.IDOutputFormatType OutputFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=5)]
        public string ToWebEnv;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=6)]
        public ServiceReference1.CompressType eCompress;
        private object testc;

        public IDExchangeRequest()
        {
        }

        public IDExchangeRequest(object testc)
        {
            this.testc = testc;
        }

        public IDExchangeRequest(string InputListKey, ServiceReference1.IDOperationType Operation, ServiceReference1.PCIDType OutputType, string OutputSourceName, ServiceReference1.IDOutputFormatType OutputFormat, string ToWebEnv, ServiceReference1.CompressType eCompress)
        {
            this.InputListKey = InputListKey;
            this.Operation = Operation;
            this.OutputType = OutputType;
            this.OutputSourceName = OutputSourceName;
            this.OutputFormat = OutputFormat;
            this.ToWebEnv = ToWebEnv;
            this.eCompress = eCompress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IDExchangeResponse", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class IDExchangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string ListKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public string DownloadKey;
        
        public IDExchangeResponse()
        {
        }
        
        public IDExchangeResponse(string ListKey, string DownloadKey)
        {
            this.ListKey = ListKey;
            this.DownloadKey = DownloadKey;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum AssayColumnsType
    {
        
        /// <remarks/>
        eAssayColumns_Complete,
        
        /// <remarks/>
        eAssayColumns_Concise,
        
        /// <remarks/>
        eAssayColumns_TIDs,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum AssayOutcomeFilterType
    {
        
        /// <remarks/>
        eAssayOutcome_All,
        
        /// <remarks/>
        eAssayOutcome_Inactive,
        
        /// <remarks/>
        eAssayOutcome_Active,
        
        /// <remarks/>
        eAssayOutcome_Inconclusive,
        
        /// <remarks/>
        eAssayOutcome_Unspecified,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InputListString", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class InputListStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public string[] strids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public ServiceReference1.PCIDType idType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=2)]
        public string SourceName;
        
        public InputListStringRequest()
        {
        }
        
        public InputListStringRequest(string[] strids, ServiceReference1.PCIDType idType, string SourceName)
        {
            this.strids = strids;
            this.idType = idType;
            this.SourceName = SourceName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InputListStringResponse", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class InputListStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string ListKey;
        
        public InputListStringResponse()
        {
        }
        
        public InputListStringResponse(string ListKey)
        {
            this.ListKey = ListKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InputStructureBase64", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class InputStructureBase64Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] structure;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=1)]
        public ServiceReference1.FormatType format;
        
        public InputStructureBase64Request()
        {
        }
        
        public InputStructureBase64Request(byte[] structure, ServiceReference1.FormatType format)
        {
            this.structure = structure;
            this.format = format;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InputStructureBase64Response", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class InputStructureBase64Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string StrKey;
        
        public InputStructureBase64Response()
        {
        }
        
        public InputStructureBase64Response(string StrKey)
        {
            this.StrKey = StrKey;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum ScoreTypeType
    {
        
        /// <remarks/>
        eScoreType_Sim2DSubs,
        
        /// <remarks/>
        eScoreType_ShapeOpt3D,
        
        /// <remarks/>
        eScoreType_FeatureOpt3D,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/")]
    public enum MatrixFormatType
    {
        
        /// <remarks/>
        eMatrixFormat_CSV,
        
        /// <remarks/>
        eMatrixFormat_IdIdScore,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Standardize", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class StandardizeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string StrKey;
        
        public StandardizeRequest()
        {
        }
        
        public StandardizeRequest(string StrKey)
        {
            this.StrKey = StrKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StandardizeResponse", WrapperNamespace="http://pubchem.ncbi.nlm.nih.gov/", IsWrapped=true)]
    public partial class StandardizeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pubchem.ncbi.nlm.nih.gov/", Order=0)]
        public string StrKey;
        
        public StandardizeResponse()
        {
        }
        
        public StandardizeResponse(string StrKey)
        {
            this.StrKey = StrKey;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface PUGSoapChannel : ServiceReference1.PUGSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class PUGSoapClient : System.ServiceModel.ClientBase<ServiceReference1.PUGSoap>, ServiceReference1.PUGSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PUGSoapClient() : 
                base(PUGSoapClient.GetDefaultBinding(), PUGSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PUGSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PUGSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PUGSoapClient.GetBindingForEndpoint(endpointConfiguration), PUGSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PUGSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PUGSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PUGSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PUGSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PUGSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> AssayDownloadAsync(string AssayKey, ServiceReference1.AssayFormatType AssayFormat, ServiceReference1.CompressType eCompress)
        {
            return base.Channel.AssayDownloadAsync(AssayKey, AssayFormat, eCompress);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DownloadResponse> DownloadAsync(ServiceReference1.DownloadRequest request)
        {
            return base.Channel.DownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ColumnDescriptionType> GetAssayColumnDescriptionAsync(int AID, ServiceReference1.HeadingType Heading, int TID)
        {
            return base.Channel.GetAssayColumnDescriptionAsync(AID, Heading, TID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetAssayColumnDescriptionsResponse> ServiceReference1.PUGSoap.GetAssayColumnDescriptionsAsync(ServiceReference1.GetAssayColumnDescriptionsRequest request)
        {
            return base.Channel.GetAssayColumnDescriptionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetAssayColumnDescriptionsResponse> GetAssayColumnDescriptionsAsync(int AID)
        {
            ServiceReference1.GetAssayColumnDescriptionsRequest inValue = new ServiceReference1.GetAssayColumnDescriptionsRequest();
            inValue.AID = AID;
            return ((ServiceReference1.PUGSoap)(this)).GetAssayColumnDescriptionsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetAssayDescriptionResponse> GetAssayDescriptionAsync(ServiceReference1.GetAssayDescriptionRequest request)
        {
            return base.Channel.GetAssayDescriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> GetDownloadUrlAsync(string DownloadKey)
        {
            return base.Channel.GetDownloadUrlAsync(DownloadKey);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.EntrezKey> GetEntrezKeyAsync(string ListKey)
        {
            return base.Channel.GetEntrezKeyAsync(ListKey);
        }
        
        public System.Threading.Tasks.Task<string> GetEntrezUrlAsync(ServiceReference1.EntrezKey EntrezKey)
        {
            return base.Channel.GetEntrezUrlAsync(EntrezKey);
        }
        
        public System.Threading.Tasks.Task<int[]> GetIDListAsync(string ListKey, int Start, int Count)
        {
            return base.Channel.GetIDListAsync(ListKey, Start, Count);
        }
        
        public System.Threading.Tasks.Task<int> GetListItemsCountAsync(string ListKey)
        {
            return base.Channel.GetListItemsCountAsync(ListKey);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.StatusType> GetOperationStatusAsync(string AnyKey)
        {
            return base.Channel.GetOperationStatusAsync(AnyKey);
        }
        
        public System.Threading.Tasks.Task<int> GetStandardizedCIDAsync(string StrKey)
        {
            return base.Channel.GetStandardizedCIDAsync(StrKey);
        }
        
        public System.Threading.Tasks.Task<string> GetStandardizedStructureAsync(string StrKey, ServiceReference1.FormatType format)
        {
            return base.Channel.GetStandardizedStructureAsync(StrKey, format);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetStandardizedStructureBase64Response> ServiceReference1.PUGSoap.GetStandardizedStructureBase64Async(ServiceReference1.GetStandardizedStructureBase64Request request)
        {
            return base.Channel.GetStandardizedStructureBase64Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetStandardizedStructureBase64Response> GetStandardizedStructureBase64Async(string StrKey, ServiceReference1.FormatType format)
        {
            ServiceReference1.GetStandardizedStructureBase64Request inValue = new ServiceReference1.GetStandardizedStructureBase64Request();
            inValue.StrKey = StrKey;
            inValue.format = format;
            return ((ServiceReference1.PUGSoap)(this)).GetStandardizedStructureBase64Async(inValue);
        }
        
        public System.Threading.Tasks.Task<string> GetStatusMessageAsync(string AnyKey)
        {
            return base.Channel.GetStatusMessageAsync(AnyKey);
        }
        
        public System.Threading.Tasks.Task<string> IdentitySearchAsync(string StrKey, ServiceReference1.IdentitySearchOptions idOptions, ServiceReference1.LimitsType limits)
        {
            return base.Channel.IdentitySearchAsync(StrKey, idOptions, limits);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.IDExchangeResponse> IDExchangeAsync(ServiceReference1.IDExchangeRequest request)
        {
            return base.Channel.IDExchangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> InputAssayAsync(int AID, ServiceReference1.AssayColumnsType Columns, string ListKeyTIDs, string ListKeySCIDs, ServiceReference1.AssayOutcomeFilterType OutcomeFilter)
        {
            return base.Channel.InputAssayAsync(AID, Columns, ListKeyTIDs, ListKeySCIDs, OutcomeFilter);
        }
        
        public System.Threading.Tasks.Task<string> InputEntrezAsync(ServiceReference1.EntrezKey EntrezKey)
        {
            return base.Channel.InputEntrezAsync(EntrezKey);
        }
        
        public System.Threading.Tasks.Task<string> InputListAsync(int[] ids, ServiceReference1.PCIDType idType)
        {
            return base.Channel.InputListAsync(ids, idType);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.InputListStringResponse> ServiceReference1.PUGSoap.InputListStringAsync(ServiceReference1.InputListStringRequest request)
        {
            return base.Channel.InputListStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InputListStringResponse> InputListStringAsync(string[] strids, ServiceReference1.PCIDType idType, string SourceName)
        {
            ServiceReference1.InputListStringRequest inValue = new ServiceReference1.InputListStringRequest();
            inValue.strids = strids;
            inValue.idType = idType;
            inValue.SourceName = SourceName;
            return ((ServiceReference1.PUGSoap)(this)).InputListStringAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> InputListTextAsync(string ids, ServiceReference1.PCIDType idType)
        {
            return base.Channel.InputListTextAsync(ids, idType);
        }
        
        public System.Threading.Tasks.Task<string> InputStructureAsync(string structure, ServiceReference1.FormatType format)
        {
            return base.Channel.InputStructureAsync(structure, format);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.InputStructureBase64Response> ServiceReference1.PUGSoap.InputStructureBase64Async(ServiceReference1.InputStructureBase64Request request)
        {
            return base.Channel.InputStructureBase64Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InputStructureBase64Response> InputStructureBase64Async(byte[] structure, ServiceReference1.FormatType format)
        {
            ServiceReference1.InputStructureBase64Request inValue = new ServiceReference1.InputStructureBase64Request();
            inValue.structure = structure;
            inValue.format = format;
            return ((ServiceReference1.PUGSoap)(this)).InputStructureBase64Async(inValue);
        }
        
        public System.Threading.Tasks.Task<string> MFSearchAsync(string MF, ServiceReference1.MFSearchOptions mfOptions, ServiceReference1.LimitsType limits)
        {
            return base.Channel.MFSearchAsync(MF, mfOptions, limits);
        }
        
        public System.Threading.Tasks.Task<string> ScoreMatrixAsync(string ListKey, string SecondaryListKey, ServiceReference1.ScoreTypeType ScoreType, ServiceReference1.MatrixFormatType MatrixFormat, ServiceReference1.CompressType eCompress, int N3DConformers, bool No3DParent)
        {
            return base.Channel.ScoreMatrixAsync(ListKey, SecondaryListKey, ScoreType, MatrixFormat, eCompress, N3DConformers, No3DParent);
        }
        
        public System.Threading.Tasks.Task<string> SimilaritySearch2DAsync(string StrKey, ServiceReference1.SimilaritySearchOptions simOptions, ServiceReference1.LimitsType limits)
        {
            return base.Channel.SimilaritySearch2DAsync(StrKey, simOptions, limits);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.StandardizeResponse> StandardizeAsync(ServiceReference1.StandardizeRequest request)
        {
            return base.Channel.StandardizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> SubstructureSearchAsync(string StrKey, ServiceReference1.StructureSearchOptions ssOptions, ServiceReference1.LimitsType limits)
        {
            return base.Channel.SubstructureSearchAsync(StrKey, ssOptions, limits);
        }
        
        public System.Threading.Tasks.Task<string> SuperstructureSearchAsync(string StrKey, ServiceReference1.StructureSearchOptions ssOptions, ServiceReference1.LimitsType limits)
        {
            return base.Channel.SuperstructureSearchAsync(StrKey, ssOptions, limits);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PUGSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PUGSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://pubchem.ncbi.nlm.nih.gov/pug_soap/pug_soap.cgi");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PUGSoapClient.GetBindingForEndpoint(EndpointConfiguration.PUGSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PUGSoapClient.GetEndpointAddress(EndpointConfiguration.PUGSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            PUGSoap,
        }
    }
}
