//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SustainableChemistry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SustainableChemistry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider: John Wiley &amp; Sons, Ltd
        ///Content:text/plain; charset=&quot;UTF-8&quot;
        ///
        ///TY  - JOUR
        ///AU  - ILIA, G.
        ///AU  - CAPRITA, A.
        ///AU  - DEHELEAN, G.
        ///TI  - ChemInform Abstract: Synthesis of Tris(2-chloroethyl)phosphate.
        ///JO  - ChemInform
        ///JA  - ChemInform
        ///VL  - 27
        ///IS  - 5
        ///PB  - WILEY-VCH Verlag
        ///SN  - 1522-2667
        ///UR  - http://dx.doi.org/10.1002/chin.199605199
        ///DO  - 10.1002/chin.199605199
        ///SP  - no
        ///EP  - no
        ///KW  - organo-phosphorus compounds, acyclic O,N,S derivatives
        ///PY  - 1996
        ///AB  - ChemInform is a weekly Abst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10_1002_2Fchin_199605199 {
            get {
                return ResourceManager.GetString("_10_1002_2Fchin_199605199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] achs_jacsat105_661 {
            get {
                object obj = ResourceManager.GetObject("achs_jacsat105_661", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] achs_oprdfk4_175 {
            get {
                object obj = ResourceManager.GetObject("achs_oprdfk4_175", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BIB {
            get {
                object obj = ResourceManager.GetObject("BIB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] europepmc {
            get {
                object obj = ResourceManager.GetObject("europepmc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] europepmc1 {
            get {
                object obj = ResourceManager.GetObject("europepmc1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;style xmlns=&quot;http://purl.org/net/xbiblio/csl&quot; class=&quot;in-text&quot; version=&quot;1.0&quot; demote-non-dropping-particle=&quot;sort-only&quot; default-locale=&quot;en-GB&quot;&gt;
        ///  &lt;info&gt;
        ///    &lt;title&gt;Cite Them Right 10th edition - Harvard&lt;/title&gt;
        ///    &lt;id&gt;http://www.zotero.org/styles/harvard-cite-them-right&lt;/id&gt;
        ///    &lt;link href=&quot;http://www.zotero.org/styles/harvard-cite-them-right&quot; rel=&quot;self&quot;/&gt;
        ///    &lt;link href=&quot;http://www.zotero.org/styles/harvard-university-of-greenwich&quot; rel=&quot;template&quot;/&gt;
        ///    &lt;link hre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HarvardCiteThemRight {
            get {
                return ResourceManager.GetString("HarvardCiteThemRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon1 {
            get {
                object obj = ResourceManager.GetObject("Icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string References1 {
            get {
                return ResourceManager.GetString("References1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] S0040403900813763 {
            get {
                object obj = ResourceManager.GetObject("S0040403900813763", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] S0040403900942163 {
            get {
                object obj = ResourceManager.GetObject("S0040403900942163", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] S0040403901904617 {
            get {
                object obj = ResourceManager.GetObject("S0040403901904617", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] S1001841712003142 {
            get {
                object obj = ResourceManager.GetObject("S1001841712003142", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
