# Generated by Django 2.1.5 on 2019-01-14 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.TextField()),
                ('CasNumber', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Smarts', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to='Images/FunctionalGroups/')),
            ],
        ),
        migrations.CreateModel(
            name='NamedReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=150)),
                ('URL', models.TextField(blank=True)),
                ('ReactantA', models.CharField(blank=True, max_length=150)),
                ('ReactantB', models.CharField(blank=True, max_length=150)),
                ('ReactantC', models.CharField(blank=True, max_length=150)),
                ('Product', models.CharField(blank=True, max_length=150)),
                ('Heat', models.CharField(blank=True, max_length=150)),
                ('Temp', models.CharField(choices=[('NA', 'None'), ('HE', 'Heat')], default='NA', max_length=2)),
                ('AcidBase', models.CharField(blank=True, max_length=150)),
                ('Temp2', models.CharField(choices=[('AC', 'Acid'), ('AB', 'Acid Or Base'), ('BA', 'Base'), ('NA', 'Not Applicable')], default='NA', max_length=2)),
                ('Catalyst', models.CharField(blank=True, max_length=150)),
                ('Solvent', models.CharField(blank=True, max_length=150)),
                ('ByProducts', models.CharField(blank=True, max_length=150)),
                ('Image', models.ImageField(upload_to='Images/Reactions/')),
            ],
        ),
        migrations.CreateModel(
            name='Reactant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.TextField()),
                ('Temp2', models.CharField(choices=[('FG', 'Functional Group'), ('CO', 'Compound')], default='CO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('RISData', models.TextField()),
                ('Functional_Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.FunctionalGroup')),
                ('Reaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.NamedReaction')),
            ],
        ),
        migrations.CreateModel(
            name='Solvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='namedreaction',
            name='ByProd',
            field=models.ManyToManyField(blank=True, related_name='ByProduct', to='app.Reactant'),
        ),
        migrations.AddField(
            model_name='namedreaction',
            name='Catal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Catalyst'),
        ),
        migrations.AddField(
            model_name='namedreaction',
            name='Functional_Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.FunctionalGroup'),
        ),
        migrations.AddField(
            model_name='namedreaction',
            name='Reactants',
            field=models.ManyToManyField(related_name='Reactant', to='app.Reactant'),
        ),
        migrations.AddField(
            model_name='namedreaction',
            name='Solv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Solvent'),
        ),
    ]
