# Generated by Django 2.1.5 on 2019-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalyst',
            name='Name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='functionalgroup',
            name='Name',
            field=models.CharField(help_text='The name of the functional group.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='functionalgroup',
            name='Smarts',
            field=models.CharField(help_text='Structure of the functional group as a SMILES string.', max_length=150),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='ByProd',
            field=models.ManyToManyField(blank=True, related_name='ByProduct', to='app.Reactant', verbose_name='Reaction By-Products:'),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Temp',
            field=models.CharField(choices=[('NA', 'None'), ('HE', 'Heat')], default='NA', max_length=2, verbose_name='Heated Reaction'),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Temp2',
            field=models.CharField(choices=[('AC', 'Acid'), ('AB', 'Acid Or Base'), ('BA', 'Base'), ('NA', 'Not Applicable')], default='NA', max_length=2, verbose_name='Acid or Base Conditions:'),
        ),
        migrations.AlterField(
            model_name='reactant',
            name='Name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='solvent',
            name='Name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
