# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedreaction',
            name='AcidBase',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='ByProducts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Catalyst',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Heat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Product',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='ReactantA',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='ReactantB',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='ReactantC',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Solvent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='URL',
            field=models.TextField(null=True),
        ),
    ]
