# Generated by Django 2.1.5 on 2019-01-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190116_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalgroup',
            name='Smarts',
            field=models.CharField(help_text='Structure of the functional group as a SMILES string.', max_length=150, unique=True),
        ),
    ]
