# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181219_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedreaction',
            name='Name',
            field=models.TextField(null=True, verbose_name='Named Reaction'),
        ),
    ]
