# Generated by Django 2.1.5 on 2019-01-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190116_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedreaction',
            name='UniqueName',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
