# Generated by Django 2.1.5 on 2019-01-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_namedreaction_uniquename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedreaction',
            name='UniqueName',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
