# Generated by Django 2.1.5 on 2019-01-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190117_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedreaction',
            name='Functional_Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.FunctionalGroup'),
        ),
    ]
