# Generated by Django 2.1.5 on 2019-01-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190117_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedreaction',
            name='UniqueName',
        ),
        migrations.AlterUniqueTogether(
            name='namedreaction',
            unique_together={('Functional_Group', 'Name')},
        ),
    ]
