# Generated by Django 2.1.5 on 2019-01-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190121_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedreaction',
            name='AcidBase',
        ),
        migrations.RemoveField(
            model_name='namedreaction',
            name='ByProducts',
        ),
        migrations.RemoveField(
            model_name='namedreaction',
            name='Catalyst',
        ),
        migrations.RemoveField(
            model_name='namedreaction',
            name='Heat',
        ),
        migrations.RemoveField(
            model_name='namedreaction',
            name='Solvent',
        ),
    ]
