# Generated by Django 2.1.5 on 2019-01-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190121_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namedreaction',
            old_name='Temp2',
            new_name='AcidBase',
        ),
        migrations.RenameField(
            model_name='namedreaction',
            old_name='ByProd',
            new_name='ByProducts',
        ),
        migrations.RenameField(
            model_name='namedreaction',
            old_name='Catal',
            new_name='Catalyst',
        ),
        migrations.RenameField(
            model_name='namedreaction',
            old_name='Temp',
            new_name='Heat',
        ),
        migrations.RenameField(
            model_name='namedreaction',
            old_name='Solv',
            new_name='Solvent',
        ),
    ]
