# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181220_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalgroup',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/FunctionalGroup/'),
        ),
    ]
