# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_functionalgroup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalgroup',
            name='Image',
            field=models.ImageField(default='Images/FunctionalGroups/th.jpg', upload_to='Images/FunctionalGroups/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='functionalgroup',
            name='Name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='functionalgroup',
            name='Smarts',
            field=models.CharField(max_length=150),
        ),
    ]
