# Generated by Django 2.1.5 on 2019-01-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_reference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalgroup',
            name='Name',
            field=models.SlugField(help_text='The name of the functional group.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Name',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
