# Generated by Django 2.1.5 on 2019-01-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190128_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalgroup',
            name='LowerName',
            field=models.CharField(default='A', help_text='The name of the functional group.', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='namedreaction',
            name='LowerName',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
