# Generated by Django 2.1.5 on 2019-01-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190128_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalgroup',
            name='LowerName',
            field=models.CharField(help_text='The name of the functional group.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='functionalgroup',
            name='Name',
            field=models.CharField(help_text='The name of the functional group.', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='namedreaction',
            unique_together={('Functional_Group', 'LowerName')},
        ),
    ]
