# Generated by Django 2.1.5 on 2019-01-29 17:36

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190128_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalgroup',
            name='Name',
            field=app.models.CICharField(help_text='The name of the functional group.', max_length=150),
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Name',
            field=app.models.CICharField(blank=True, max_length=150),
        ),
    ]
