# Generated by Django 2.1.5 on 2019-01-29 17:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190129_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalgroup',
            name='LowerName',
            field=models.CharField(help_text='The name of the functional group.', max_length=150),
        ),
        migrations.AlterField(
            model_name='functionalgroup',
            name='Name',
            field=app.models.CICharField(help_text='The name of the functional group.', max_length=150, unique=True),
        ),
    ]
