# Generated by Django 2.1.5 on 2019-01-30 15:32

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190129_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedreaction',
            name='LowerName',
        ),
        migrations.AlterField(
            model_name='namedreaction',
            name='Name',
            field=app.models.CICharField(max_length=150),
        ),
    ]
