# Generated by Django 2.1.5 on 2019-01-30 15:43

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190130_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionalgroup',
            name='LowerName',
        ),
        migrations.AlterField(
            model_name='catalyst',
            name='Name',
            field=app.models.CICharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='Name',
            field=app.models.CICharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='reactant',
            name='Name',
            field=app.models.CICharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='solvent',
            name='Name',
            field=app.models.CICharField(max_length=150, unique=True),
        ),
    ]
