//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from smiles.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="smilesParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IsmilesListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.smiles"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSmiles([NotNull] smilesParser.SmilesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.smiles"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSmiles([NotNull] smilesParser.SmilesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.chain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChain([NotNull] smilesParser.ChainContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.chain"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChain([NotNull] smilesParser.ChainContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.branched_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBranched_atom([NotNull] smilesParser.Branched_atomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.branched_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBranched_atom([NotNull] smilesParser.Branched_atomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBranch([NotNull] smilesParser.BranchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.branch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBranch([NotNull] smilesParser.BranchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.ringbond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRingbond([NotNull] smilesParser.RingbondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.ringbond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRingbond([NotNull] smilesParser.RingbondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.bond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBond([NotNull] smilesParser.BondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.bond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBond([NotNull] smilesParser.BondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.dot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDot([NotNull] smilesParser.DotContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.dot"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDot([NotNull] smilesParser.DotContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] smilesParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] smilesParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbol([NotNull] smilesParser.SymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbol([NotNull] smilesParser.SymbolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.organic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrganic([NotNull] smilesParser.OrganicContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.organic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrganic([NotNull] smilesParser.OrganicContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.aromatic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAromatic([NotNull] smilesParser.AromaticContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.aromatic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAromatic([NotNull] smilesParser.AromaticContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.halogen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHalogen([NotNull] smilesParser.HalogenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.halogen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHalogen([NotNull] smilesParser.HalogenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWildcard([NotNull] smilesParser.WildcardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.wildcard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWildcard([NotNull] smilesParser.WildcardContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.chiral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChiral([NotNull] smilesParser.ChiralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.chiral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChiral([NotNull] smilesParser.ChiralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.charge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharge([NotNull] smilesParser.ChargeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.charge"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharge([NotNull] smilesParser.ChargeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.hcount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHcount([NotNull] smilesParser.HcountContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.hcount"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHcount([NotNull] smilesParser.HcountContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.atomclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomclass([NotNull] smilesParser.AtomclassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.atomclass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomclass([NotNull] smilesParser.AtomclassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.isotope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsotope([NotNull] smilesParser.IsotopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.isotope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsotope([NotNull] smilesParser.IsotopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="smilesParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] smilesParser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="smilesParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] smilesParser.ElementContext context);
}
