//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChemInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;list id=&quot;chemicalElement&quot; convention=&quot;bodr:elements&quot;
        ///      title=&quot;properties of the elements&quot;
        ///
        ///      xmlns=&quot;http://www.xml-cml.org/schema&quot; 
        ///      xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot; 
        ///      xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        ///      xmlns:bo=&quot;http://www.blueobelisk.org/dict/terminology&quot; 
        ///      xmlns:boUnits=&quot;http://www.blueobelisk.org/dict/units&quot; 
        ///      xmlns:units=&quot;http://www.xml-cml.org/units/units&quot; 
        ///      xmlns:siUnits=&quot;http: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phosphine	OP(O)O
        ///phosphite	OP(C)O
        ///phosphonite	OP(C)C
        ///phosphinite	CP(C)C
        ///phosphoramidite	NP(O)O
        ///phosphorodiamidite	NP(N)O
        ///phosphonamidite	OP(N)C
        ///phosphorothioite	OP(O)S
        ///phosphorodithioite	OP(S)S
        ///phosphate	OP(=O)(O)O
        ///phosphonate	OP(=O)(O)C
        ///phosphinate	OP(=O)(C)C
        ///phosphine oxide	CP(=O)(C)C
        ///phosphoramidate	OP(=O)(N)O
        ///phosphorodiamidate	OP(=O)(N)N
        ///phosphoramide	NP(=O)(N)N
        ///phosphonamidate	NP(=O)(C)O
        ///phosphonamide	NP(=O)(C)C
        ///phosphinamide	OP(=S)(O)O
        ///phosphorothioate	OP(=S)(O)S
        ///phosphorodithioat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phosphate_Functional_Groups {
            get {
                return ResourceManager.GetString("Phosphate_Functional_Groups", resourceCulture);
            }
        }
    }
}
